### ISSUE TITLE
Single suite

### ISSUE THREAD

**Issue by aydin41k** [aydin41k/-JS-Card-Game#15]
At the moment, each card is picked randomly from "a new deck", i.e. deck is not saved after each card is picked. Each round should be dealt from the same stack, i.e. a card can't be duplicated on either player's hand.

**Comment by Aspireve** [comment]
Hey @aydin41k, could I work on this?

**Comment by aydin41k** [comment]
Sure thing @Aspireve , go for it

**Comment by Aspireve** [comment]
Hi @aydin41k, 
I completed working on it.
I used a debug console print line to show when the card changed (it prints it in the console), Ill remove it while making the PR
![image](https://user-images.githubusercontent.com/93852415/197704127-7171be11-ea5a-489d-be18-5f0cad34eae5.png)
It works something like this
Is it fine?

**Comment by aydin41k** [comment]
Hi @Aspireve !
Can you open a PR, so that I can see what the code does? I'll comment in the PR.
Cheers

**Comment by Aspireve** [comment]
Hi @aydin41k, I just made the PR do review it and tell me if anything more needs to be added.
Thanks You.

**Comment by aydin41k** [comment]
I merged your code @Aspireve , I'll roll it out to the website later.
Thank you for your contribution!

**Comment by aydin41k** [comment]
@Aspireve Also, can you open another PR and add your name and photo to Readme.md please?
